### ISSUE TITLE
Error: search AndroidManifest.xml in gradle project

### ISSUE THREAD

**Issue by talenguyen** [KeepSafe/android-resource-remover#56] opened 2016-09-11 05:16 UTC
For **gradle** project, _AndroidManifest.xml_ file normally placed in `app/src/main/AndroidManifest.xml` but this library always find in `app/AndroidManifest.xml` then never see it.

**Comment by LukeLinXu** [comment] 2016-09-13 20:02
same here.

**Comment by LukeLinXu** [comment] 2016-09-13 20:14
should be duplicate of #53

**Closed** 2016-09-14 03:44 UTC
